In [16]:
import networkx as nx
G = nx.Graph()

In [17]:
G.add_nodes_from([1,2,3])
G.add_edge(3,4)

In [18]:
print(G.nodes())
print(G.edges())

[1, 2, 3, 4]
[(3, 4)]


In [20]:
import matplotlib.pyplot as plt
nx.draw(G)
plt.show()


<ipython-input-20-2623cf771fd5>:3: UserWarning: Matplotlib is currently using ps, which is a non-GUI backend, so cannot show the figure.
  plt.show()


In [22]:
FG = nx.Graph()
FG.add_weighted_edges_from([(1, 2, 0.125), (1, 3, 0.75), (2, 4, 1.2), (3, 4, 0.375)])
for n, nbrs in FG.adj.items():
   for nbr, eattr in nbrs.items():
       wt = eattr['weight']
       if wt < 0.5: print(f"({n}, {nbr}, {wt:.3})")

(1, 2, 0.125)
(2, 1, 0.125)
(3, 4, 0.375)
(4, 3, 0.375)


In [24]:
for (u, v, wt) in FG.edges.data('weight'):
    if wt < 0.5:
        print(f"({u}, {v}, {wt:.3})")

(1, 2, 0.125)
(3, 4, 0.375)


In [33]:
DG = nx.DiGraph()
DG.add_weighted_edges_from([(1, 2, 0.5), (3, 1, 0.75)])
DG.out_degree(1, weight='weight')
print(DG.adj.items())
print(list(DG.predecessors(1)))
print(list(DG.successors(1)))

ItemsView(AdjacencyView({1: {2: {'weight': 0.5}}, 2: {}, 3: {1: {'weight': 0.75}}}))
[3]
[2]


In [35]:
import numpy as np
a = np.random.randint(0, 2, size=(10, 10))
print(a)

[[0 1 0 1 0 0 1 1 0 0]
 [1 0 1 1 1 1 0 1 0 1]
 [0 1 0 0 1 1 1 1 0 1]
 [0 0 1 0 0 0 0 1 1 1]
 [1 0 0 1 1 1 0 1 1 1]
 [0 0 0 0 0 0 0 0 1 1]
 [0 0 1 0 0 0 1 1 1 1]
 [1 0 1 0 0 1 1 0 0 0]
 [1 1 1 1 1 0 1 0 0 0]
 [1 1 1 0 0 0 0 0 0 1]]


In [36]:
D = nx.DiGraph(a)

In [40]:
D.nodes()
D.edges()
nx.to_numpy_array(D)

array([[0., 1., 0., 1., 0., 0., 1., 1., 0., 0.],
       [1., 0., 1., 1., 1., 1., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1., 1., 1., 1., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 1., 1., 1.],
       [1., 0., 0., 1., 1., 1., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 1., 0., 0., 0., 1., 1., 1., 1.],
       [1., 0., 1., 0., 0., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 1.]])