## syft==0.2.4 教程

## 1 send tensor to bob's machine

In [2]:
import numpy as np 
import syft as sy # Run this cell to see if things work
import sys

import torch
from torch.nn import Parameter
import torch.nn as nn
import torch.nn.functional as F

import syft as sy
hook = sy.TorchHook(torch)

torch.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

In [3]:
x = torch.tensor([1,2,3,4,5])
y = x + x
print(y)

tensor([ 2,  4,  6,  8, 10])


In [32]:
bob = sy.VirtualWorker(hook, id="bob")

In [5]:
x = torch.tensor([1,2,3,4,5])
y = torch.tensor([1,1,1,1,1])

In [22]:
x_ptr = x.send(bob)
y_ptr = y.send(bob)
print(x_ptr)
print(y_ptr)
x_ptr.location
x_ptr.id_at_location
x_ptr.owner

(Wrapper)>[PointerTensor | me:2749667760 -> bob:24084234239]
(Wrapper)>[PointerTensor | me:90763379457 -> bob:66772298697]


<VirtualWorker id:me #objects:0>

In [8]:
bob._objects

{24084234239: tensor([1, 2, 3, 4, 5]), 66772298697: tensor([1, 1, 1, 1, 1])}

In [16]:
z = x_ptr + x_ptr
print(z)

(Wrapper)>[PointerTensor | me:43302083549 -> bob:80050839170]


In [33]:
bob._objects

{24084234239: tensor([1, 2, 3, 4, 5]),
 66772298697: tensor([1, 1, 1, 1, 1]),
 44465068457: tensor([ 2,  4,  6,  8, 10]),
 57491926079: tensor([1, 2, 3, 4, 5]),
 11932127750: tensor([1, 1, 1, 1, 1])}

## 2 using tensor pointer

In [38]:
bob = sy.VirtualWorker(hook, id="tom")

In [39]:
x = torch.tensor([1,2,3,4,5]).send(bob)
y = torch.tensor([1,1,1,1,1]).send(bob)
z = x+y
print(z)

(Wrapper)>[PointerTensor | me:41193493464 -> tom:49833880055]


In [40]:
bob._objects

{78395822529: tensor([1, 2, 3, 4, 5]),
 72335892048: tensor([1, 1, 1, 1, 1]),
 49833880055: tensor([2, 3, 4, 5, 6])}

In [41]:
z.get()

tensor([2, 3, 4, 5, 6])

In [42]:
bob._objects

{78395822529: tensor([1, 2, 3, 4, 5]), 72335892048: tensor([1, 1, 1, 1, 1])}

In [43]:
x = torch.tensor([1,2,3,4,5.], requires_grad=True).send(bob)
y = torch.tensor([1,1,1,1,1.], requires_grad=True).send(bob)
z = (x + y).sum()
z.backward()
x = x.get()
print(x)
print(x.grad)

tensor([1., 2., 3., 4., 5.], requires_grad=True)
